# Exemples Àlgebra

In [1]:
import numpy as np

Exemples de vectors (array)

In [2]:
v=np.array([1,0,0])
u=np.array([0,-2,0])

In [4]:
print(u)

[ 0 -2  0]


Operacions amb vectors (suma, resta, producte escalar i vectorial)

In [5]:
w1=u+v
print(w1)
w2=u-v
print(w2)

[ 1 -2  0]
[-1 -2  0]


In [6]:
a=np.dot(u,v) #np.dot es per fer producte escalar
print(a)

0


In [7]:
b=np.cross(u,v) #np.cross es per producte vectorial
print(b)

[0 0 2]


Exemple amb Matrius

In [9]:
A=np.array([[2,4],[1,3]])
print(A)

[[2 4]
 [1 3]]


In [14]:
e=A[0,1] # 0 es la fila i 1 es la columna
print(e)

4


In [16]:
v=A[0,:] #els : es per agafar tots vectors de la fila 0. És com un comodin
print(v)

[2 4]


In [18]:
u=A[:,1] # agafa tots els valors de la columna 1
print(u)

[4 3]


Diagonalitzem matrius (busquem valors i vectors propis)

In [19]:
A=np.array([[2,2],[1,3]])

In [22]:
Valors,Vectors = np.linalg.eig(A) # np.linalg.eig8) per veure valors i vectos propis
print("Valors propis", Valors)
print("Vectors propis", Vectors)

Valors propis [1. 4.]
Vectors propis [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [23]:
u=Vectors[:,0] # posem aixo per extreure els vector propi de la primera columna
print(u)

[-0.89442719  0.4472136 ]


comprovem que efectivament son vectors propis

In [25]:
# per multiplicar matrius es la mteixa comnda que amb vectors. S'han de poder multiplicar. np.dot
z=np.dot(A,u)
print(z)

[-0.89442719  0.4472136 ]


In [24]:
v=Vectors[:,1] # posem aixo per extreure els vector propi de la segona columna
print(v)

[-0.70710678 -0.70710678]


In [26]:
z2=np.dot(A,v)
print(z2)

[-2.82842712 -2.82842712]


Altres exemples de matrius

In [28]:
A=np.zeros([3,3]) #per crear matrius de zeros
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
